"""Add otp_code and otp_expires_at to User model

Revision ID: 36fd18bb37f8
Revises: 798ecd6e892e
Create Date: 2025-03-23 23:17:48.715036

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36fd18bb37f8'
down_revision = '798ecd6e892e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('otp_code', sa.String(length=6), nullable=True))
        batch_op.add_column(sa.Column('otp_expires_at', sa.DateTime(), nullable=True))
        batch_op.drop_column('otp_secret')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('otp_secret', sa.VARCHAR(length=16), autoincrement=False, nullable=False))
        batch_op.drop_column('otp_expires_at')
        batch_op.drop_column('otp_code')

    # ### end Alembic commands ###
